apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cluster entrypoint for this environment.
# This path is reconciled by flux-system and should define Flux CRs only.
resources:
  - ./flux-system
  - ./infrastructure.yaml
  - ./tls.yaml
  - ./apps.yaml
