apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./photo-api-source.yaml
  - ./photo-api-release.yaml
  - ./photo-spa.yaml
  - ./photo-spa-tls-secret.yaml
