apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photo-api
  namespace: photo
spec:
  interval: 10m
  chart:
    spec:
      chart: ./helm/photo-api
      sourceRef:
        kind: GitRepository
        name: photo-api
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  values:
    photoApi:
      replicaCount: 1
      service:
        type: LoadBalancer
    resizeApi:
      replicaCount: 1
      dapr:
        enabled: false
    blobemu:
      service:
        type: ClusterIP
    otelCollector:
      enabled: false
    daprComponent:
      enabled: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: photo-api
            patch: |
              - op: add
                path: /metadata/labels/bgp
                value: public
              - op: add
                path: /metadata/annotations
                value:
                  dns.mikrotik/enabled: "true"
                  dns.mikrotik/hostname: "photo-api.internal.bellee.net"
                  dns.mikrotik/comment: "Photo API service"
          - target:
              kind: StatefulSet
              name: blobemu
            patch: |
              - op: add
                path: /spec/template/spec/volumes
                value:
                  - name: blobemu-data
                    emptyDir: {}
              - op: replace
                path: /spec/volumeClaimTemplates
                value: []
              - op: replace
                path: /spec/template/spec/containers/0/env/0/value
                value: ""
          - target:
              kind: StatefulSet
              name: rabbitmq
            patch: |
              - op: add
                path: /spec/template/spec/volumes
                value:
                  - name: rabbitmq-data
                    emptyDir: {}
              - op: replace
                path: /spec/volumeClaimTemplates
                value: []
