creation_rules:
  - path_regex: ^gitops/platform/mikrotik-dns-controller/secret\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age14duyaevx6xguck5dmf75gkz4pkf8qlps2rlnlyzlj2wqq83vzquslucpe8
