[primary_control_plane]
kube-cp-01 ansible_host=192.168.89.10

[control_plane]
kube-cp-01 ansible_host=192.168.89.10
kube-cp-02 ansible_host=192.168.89.11
kube-cp-03 ansible_host=192.168.89.12

[workers]
kube-wk-01 ansible_host=192.168.89.20
kube-wk-02 ansible_host=192.168.89.21
kube-wk-03 ansible_host=192.168.89.22

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3

cp_endpoint_alias=kube-cluster-01
cp_endpoint_node=kube-cp-01
cp_endpoint_ip=192.168.89.10

k8s_version=1.35.6
k8s_channel=1.35
k8s_repo=https://pkgs.k8s.io/core:/stable:/v1.35/deb/
k8s_url_apt_key=https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key

pod_network_cidr=10.244.0.0/16
service_cidr=10.96.0.0/12
cri_socket=unix:///run/containerd/containerd.sock

cilium_version=1.18.3
cilium_cluster_pool_ipv4_cidr=10.0.0.0/8
cilium_reconcile_existing=false

cilium_bgp_enabled=true
cilium_bgp_reconcile_existing=false
cilium_bgp_local_asn=64512
cilium_bgp_peer_asn=64512
cilium_bgp_peer_address=192.168.89.1

cilium_bgp_cluster_config_name=cilium-bgp-cluster
cilium_bgp_instance_name=instance-64512
cilium_bgp_peer_name=peer-to-mikrotik
cilium_bgp_peer_config_name=cilium-bgp-peer

cilium_bgp_advertisement_name=cilium-bgp-advertisement
cilium_bgp_advertisement_label_key=advertise
cilium_bgp_advertisement_label_value=bgp

cilium_lb_ip_pool_name=cilium-lb-ip-pool
cilium_lb_ip_pool_cidr=172.17.0.0/16
