apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:GYvf6MA=,iv:7x2e1p+Yd4QGS8DEwx49oGmp9UVOQhMtXlfR3ptCz7c=,tag:0pNWYH4xILYBSkt5Mq5Tgw==,type:str]
    admin-password: ENC[AES256_GCM,data:Tb8pCvnNxSIq9g==,iv:bKdcmourtpjcDMNXSQioWv+wONBrdN+pjkSHof7F0Ew=,tag:UtKZcPwQGu/wuaoXBsdJXA==,type:str]
sops:
    age:
        - recipient: age14duyaevx6xguck5dmf75gkz4pkf8qlps2rlnlyzlj2wqq83vzquslucpe8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQmllT1RJMTZXT0pnR0pY
            blptbkZSd1VzM2U0dWZrV2lsaEJvZGdBM2hNCmY4NUZvMTZtd3dxMmdvd25nYVlw
            Uk1BV1g5VkcwV0NwNS9DYlZaOG9wamcKLS0tIGQ5S0xYLzczV0YwSUF6MzI1RmlV
            N1VQd1prRXYyQ3dBVjRxNW9wVkwvbnMKS9O4rNUlbiwjpx+EfGWPi4hH3mTGbFfZ
            M30MMXFWfHz3u3co8jV1azqUHZf43ptXUmoRACaL4YeRh5q1JKcpsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T04:15:50Z"
    mac: ENC[AES256_GCM,data:VNoWMrQdgRzzHf+xPs4VoDfKTE+XeJwEXy2b1DumSPwW/xH07S1pTgpusb4IqLEodicoHaVDbYfIVseD7cgCMPryXMOp4wJZ3IIfJ3BRZ85zNrMhytZ+4HMxJ5Q+8MD7rtwd2PdumI9R15h5KkMzjc9vAXOA2WZni28rBEiQlRo=,iv:6y4JyA4KCOyqgVMHVL/7u2dDObpnuvMiaxvzjGbxjTs=,tag:LovEcM5Hfc5nVDmTjYrJnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
