apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-credentials
    namespace: mikrotik-dns-controller
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:c3/ojtYCymG1Yef/,iv:VUy6xWZ4z+Oika2x3siCmjtyDA2MHM/O8y074eMTgYE=,tag:1blG/w8O3LOx79Bx9XnVnw==,type:str]
    username: ENC[AES256_GCM,data:3cVxokxrv0M=,iv:KcxST16IHGyvNiVFOPc/ZDC6akHX4xQheLsT0CDk8BU=,tag:VT4sozDEoETiGD33iCfotg==,type:str]
    password: ENC[AES256_GCM,data:kTX9b8ASZ1wTVA==,iv:uBGYvLzR8bPafv7ypzoLDvn+7q8bbwPeOKca5q0njZo=,tag:tAbgU0yhFdOCsCf3r/X/Xw==,type:str]
    insecure: ENC[AES256_GCM,data:6XTK0Q==,iv:ejIjU0T41O9JqUMfw9/NrkARfU0o+7rqZezqddRqbgI=,tag:CmaZobce8n7giqOxWiu+2A==,type:str]
sops:
    age:
        - recipient: age14duyaevx6xguck5dmf75gkz4pkf8qlps2rlnlyzlj2wqq83vzquslucpe8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQTc1b2FPWmgxMDd3Ry9y
            bEw1c01Tc0VrTG01SDY2ZktxaVZDRGs3blVNCnZMMkVaRkowbGozQ0x0NzZyMWVI
            V0hKYkNwWDZRYk10MlFGWjNsSWVrcWsKLS0tIGJKRW55SVE2Q1JkWktlVkpxRlVC
            c2V6VkIzMFlKa051TkxSZ2pJWDQyM1kKHVJCT/b3ARiYR5b32tcSjk1xME0mRQA5
            BQHJqDpM3YS+E572Egaj07RCxcx2a+NtozMFnZfonQsCgBC9Vgwdkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T02:09:13Z"
    mac: ENC[AES256_GCM,data:cF7PTeKgh4FhWCfoHEe4qQYcCJbBP9QawldnXBkgMtNKaEtztBY3EVMdAggOIFGTdVfQ1CKSfsTYiew3mN9VQgF8hJjQiYtTjeEZRsVBsfaKzt1jiY6PJkAlQe2j1ALliHZ3Bxw360/k1Rl+8fXDHTG6gVrzvWziU8nXAChiH0w=,iv:2/AYg9OYAGXqrdyiJxKlC/M75rbmpvK9XC8cgaK138Q=,tag:Bilk9JHwq6qQjcLONl0YJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
