apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cluster-level platform services and networking primitives.
resources:
  - ./cilium-bgp/cilium-ip-pool.yaml
  - ./cilium-bgp/cilium-bgp-peer-config.yaml
  - ./cilium-bgp/cilium-bgp-cluster-config.yaml
  - ./cilium-bgp/cilium-bgp-advertisement.yaml
