- hosts: primary_control_plane
  become: true
  tasks:
    - name: Generate join command for workers
      become_user: ubuntu
      shell: kubeadm token create --print-join-command
      register: worker_join_command_raw

    - name: Set join command fact
      set_fact:
        worker_join_command: "{{ worker_join_command_raw.stdout }}"

- hosts: all
  become: true
  vars:
    primary_cp_host: "{{ groups['primary_control_plane'][0] }}"
  tasks:
    - name: Fail if target_node is not provided
      ansible.builtin.fail:
        msg: "target_node is required (for example: -e target_node=kube-wk-01)"
      when: target_node is not defined

    - name: Join worker node
      shell: |
        {{ hostvars[primary_cp_host].worker_join_command }} \
          --node-name={{ inventory_hostname }} \
          --cri-socket={{ cri_socket }} \
          --v=5 > /root/kubeadm_worker_join.txt
      when: target_node is defined and inventory_hostname == target_node

    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted
      when: target_node is defined and inventory_hostname == target_node
